name: subscription_tracker
description: A subscription tracking app with usage monitoring and notifications
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  intl: ^0.18.1
  uuid: ^4.2.1
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3
  flutter_staggered_animations: ^1.1.1
  timezone: ^0.9.2
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 